name: spa_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - openpyxl=3.1.2
  - deap=1.4.1
  - scipy=1.13.1
  - pingouin=0.5.4
  - xlsxwriter=3.2.0
  - statsmodels=0.14.2        # optional, for EDA
  - scikit-posthocs=0.7.0     # optional, for EDA
